# Workflow's name
name: linux-gcc

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta4/premake-5.0.0-beta4-linux.tar.gz -O /tmp/premake5.tar.gz
          tar -xzf /tmp/premake5.tar.gz -C /tmp
          chmod +x /tmp/premake5
          /tmp/premake5 build
      - name: Test
        run: chmod +x moon && ./moon example/test/main_test.lua

