
# Workflow's name
name: windows-vs2022

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  windows-vs2022:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup premake
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta1"
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          msbuild /m Server.sln /p:configuration="release"
      - name: Test
        run: .\moon.exe test/main_test.lua

